if executable("ag")
    set grepprg=ag\ --nogroup\ --nocolor
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" ace
autocmd BufNewFile,BufRead *.ace setl sw=2 sts=2 et

" XML
autocmd filetype xml map <LocalLeader>l :%!xmllint --format -<CR>

" enable indentation for filetype plugins
filetype on
filetype plugin indent on

" enable ruler and always turn on status bar
set ruler
set laststatus=2
set statusline=%F%m%r%h%w\ [%l,%v#%o]\ %p%%

" enable syntax highlighting
syntax on

" enable ignore case and smartcase
set ic
set scs

" enable incremental search
set is

" show command in last line of the screen
set showcmd

" set up indentation using '4 whitespace chars' style
set ts=4
set shiftwidth=4
set softtabstop=4
set expandtab

" enable mouse in console
set mouse=a
set autoread

set nu

" enable visual bell
set vb

" disable entering ex mode
nnoremap Q <nop>

" Avoiding the "Hit ENTER to continue" prompts
set shortmess=aoOtI

call plug#begin()
Plug 'fatih/vim-go'
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'altercation/vim-colors-solarized'
Plug 'tpope/vim-fugitive'
Plug 'majutsushi/tagbar'
Plug 'kien/ctrlp.vim'
call plug#end()

set background=dark
colorscheme Tomorrow-Night

" use goimports
let g:go_fmt_command = "goimports"

" enable go fmt on save
let g:go_fmt_autosave = 1

" disable gopath autodetect
let go_autodetect_gopath=0

" my gometalinter cmd
let g:go_metalinter_command="gometalinter --cyclo-over=12 --deadline=60s"
