" Vundle
set nocompatible

filetype off
filetype plugin indent off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

" My Bundles
Bundle 'wgibbs/vim-irblack'
Bundle 'kml/vim-irblack-plus'
Bundle 'davidhalter/jedi-vim'
Bundle 's-urbaniak/ropevim'

" Python
autocmd filetype python set listchars=tab:>.,trail:.,extends:#,nbsp:.

" Google Go
filetype off
set runtimepath+=$GODIST/misc/vim

autocmd filetype go map K <Plug>(godoc-keyword)
autocmd filetype go map <LocalLeader>l :Fmt<CR>
autocmd filetype go set noexpandtab

" Global settings

" enable indentation for filetype plugins
filetype on
filetype plugin indent on

" show relative numbers in side bar
set relativenumber

" enable syntax highlighting
syntax on

" show command in last line of the screen
set showcmd

" set up indentation using '4 whitespace chars' style
set ts=4
set shiftwidth=4
set softtabstop=4
set expandtab

let mapleader = ","
let maplocalleader = ","
