#!/bin/bash

set -eoux -pipefail

export GDK_BACKEND=x11

read year

dialog \
    --clear \
    --backtitle "Login" \
    --title "DPI selection" \
    --menu "Options:" \
    10 30 3 \
    1 "HiDPI 4K" \
    2 "HiDPI HD" \
    3 "LoDPI" \
    2>&1 >>~/dialog.log

choice=2
logger "dpi setting: ${choice}"

case "${choice}" in
    1)
        # 192 dpi
        logger "setting up HiDPI 4k"
        export GDK_SCALE=3
        export GDK_DPI_SCALE=0.5
        export QT_SCALE_FACTOR=3
        ln -sf ~/src/dotfiles/config/xresources/4k-hidpi ~/.Xresources
        ;;
    2)
        # 96 dpi
        logger "setting up HiDPI HD"
        export GDK_SCALE=2
        export GDK_DPI_SCALE=1
        export QT_SCALE_FACTOR=2
        ln -sf ~/src/dotfiles/config/xresources/hd-hidpi ~/.Xresources
        ;;
    *)
        # 72 dpi
        logger "setting up LoDPI"
        export GDK_SCALE=1
        export GDK_DPI_SCALE=1
        export QT_SCALE_FACTOR=1
        ln -sf ~/src/dotfiles/config/xresources/lodpi ~/.Xresources
        ;;
esac

xrdb -merge ~/.Xresources

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh
echo UPDATESTARTUPTTY | gpg-connect-agent

exec i3
