export EDITOR="code --wait"
export LANG=en_US.UTF-8

BLACK='\e[0;30m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'
BLUE='\e[0;34m'
MAGENTA='\e[01;35m'
CYAN='\e[0;36m'
WHITE='\e[0;37m'

source <($HOME/bin/oc completion bash)
source <(kubectl completion bash)
source /etc/profile.d/bash_completion.sh
source /usr/share/fzf/shell/key-bindings.bash
source /usr/share/git-core/contrib/completion/git-prompt.sh

# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=

# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# enable colors in hh
export HH_CONFIG=hicolor         # get more colors

export TERM=xterm-256color

### prompt setup

function _prompt() {
    exit_code=$?

    # Save and reload the history after each command finishes
    history -a
    echo -ne "\033]0;$(dirs -0)\007"

    pwd > "${HOME}/.cwd"
}

PROMPT_COMMAND=_prompt

PS1="$(echo \$?) \[$GREEN\]\A \[$MAGENTA\]\h \[$YELLOW\]\w\[$RED\]\$(__git_ps1)\n\[\033[0m\]$ "

### other settings

# append to history, don't overwrite it
shopt -s histappend

# configure glob
shopt -s globstar
shopt -s nocaseglob

# disable XON/XOFF flow control, to enable C-s forward history search
[[ $- == *i* ]] && stty -ixon

source /etc/profile.d/vte.sh

# register direnv
eval "$(direnv hook bash)"

# export PATH=$PATH:$HOME/src/pyenv/bin
# eval "$(pyenv init -)"
